### ISSUE TITLE
Add Workbox exercices

### ISSUE THREAD

**Issue by jefBinomed** [sfeir-open-source/sfeir-school-pwa#21]

**Comment by jefBinomed** [comment]
pour l'instant il y a workbox de présent mais l'exercice n'est pas vraiment travaillé, il faut le revoir pour challenger un peu les capacités de workbox

**Comment by SetiZ** [comment]
on peut s'inspirer du codelab suivant : https://codelabs.developers.google.com/codelabs/pwa-workbox/index.html

**Comment by jefBinomed** [comment]
Bonne idée en effet !

**Comment by SetiZ** [comment]
En faisant le codelab, j'ai pas trouvé beaucoup de différences avec ce qui existe déjà. Le plan qu'on peut faire : 

1. Import script
2. precacheAndRoute
3. Routing
4. custom cache strategy

**Comment by jefBinomed** [comment]
t'intègrerais pas la phase cli ? celle qui permet de choisir en cli les fichiers de ton appcache ?

De même est ce qu'on rajouterais pas un plugin ? genre le plugin de push ? pour montrer que Workbox peut vous aider à gérer aussi les nouveaux événements du service worker ?

**Comment by SetiZ** [comment]
Bonne idée pour la phase CLI. On peut rajouter cette partie.
Je ne trouve pas le plugin de push, tu peux m'indiquer où trouver les plugins ?

**Comment by jefBinomed** [comment]
ici : https://developers.google.com/web/tools/workbox/guides/using-plugins par contre en effet, c'est pas un plugin pour le push mais juste je me disais qu'on pourrait exposer un peu les politiques de cache offertes par workbox (vu qu'on présente les stratégies dans nos slides)

Aussi regarder si dans la partie advanced workbox, y a pas un truc qui pourrait être pertinant ?

**Comment by SetiZ** [comment]
ça marche. Je vais rajouter la partie CLI puis les politiques de cache puis je vais fouiller du coté de quelques trucs bonus à rajouter.
